### ISSUE TITLE
require_login called in incorrect location

### ISSUE THREAD

**Issue by danmarsden** [manieer/moodle-block_report_certificates#3]
this require_login shouldn't be there:

https://github.com/manieer/moodle-block_report_certificates/blob/master/block_report_certificates.php#L34

**Comment by danmarsden** [comment]
you shouldn't need to include config.php in that file either:
https://github.com/manieer/moodle-block_report_certificates/blob/master/block_report_certificates.php#L29

you could add a line like this to the top of that file like some of the other blocks.

defined('MOODLE_INTERNAL') || die();

**Comment by manieer** [comment]
Thanks Dan. Will be uploading a newer version soon.
